services:
  users:
    image: ghcr.io/arquisoft/yovi_es2a-users:latest
    container_name: users
    ports:
      - "3000:3000"
    env_file:
      - ./users_env.env
    networks:
      - monitor-net

  webapp:
    build:
      context: ./webapp
      args:
        - VITE_API_URL=http://${DEPLOY_HOST}:3000
    container_name: webapp
    image: ghcr.io/arquisoft/yovi_es2a-webapp:latest
    ports:
      - "80:80"
    depends_on:
      - users
    networks:
      - monitor-net

  gamey:
    build: ./gamey
    container_name: gamey
    image: ghcr.io/arquisoft/yovi_es2a-gamey:latest
    ports:
      - "4000:4000"
    networks:
      - monitor-net

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./users/monitoring/prometheus:/etc/prometheus
    networks:
      - monitor-net

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "9091:3000"
    volumes:
      - ./users/monitoring/grafana/provisioning:/etc/grafana/provisioning
    networks:
      - monitor-net

networks:
  monitor-net:
    driver: bridge